return {
    IncompatibleType = "Data type '%s' is incompatible",
    NotAnimatable = "%s is not an animatable object type",
    FailedCreation = "%s could not be created; '%s'",

    InvalidType = "Expected type %s; got '%s'",
    InvalidKey = "Expected valid key type; got '%s'",
    InvalidClass = "'%s' is not an instance class name",
    InvalidPropOrEvent = "'%s' is not a property/event of the %s class"
}
