name: Release

on:
  push:
    tags:
      - 'v*.*.*'

permissions:
  contents: write
  pages: write
  id-token: write

jobs:
    changelog:
        name: Changelog
        runs-on: ubuntu-latest
        outputs:
          release-body: ${{ steps.update-changelog.outputs.release-notes }}
        steps:
          - uses: actions/checkout@v4
            with:
              ref: main

          - name: Update changelog
            id: update-changelog
            uses: thomaseizinger/keep-a-changelog-new-release@3.1.0
            with:
              tag: ${{ github.ref_name }}
              changelogPath: 'docs/changelog.md'

          - name: Commit changelog
            uses: actions-js/push@v1.5
            with:
              message: 'docs(release): publish ${{ github.ref_name }}'
              github_token: ${{ secrets.GITHUB_TOKEN }}

    build:
        name: Build
        runs-on: ubuntu-latest
        needs: changelog
        steps:
          - uses: actions/checkout@v4
            with:
              ref: main

          - name: Setup Pesde
            uses: lumin-org/setup-pesde@v0.4.1
            with:
              version: 'v0.6.0-rc.7+registry.0.2.0-rc.3'
              cache: true

          - name: Install dependencies
            run: pesde install

          - name: Build
            run: rojo build standalone.project.json --output ./standalone.rbxm

          - name: Release
            uses: softprops/action-gh-release@v2.2.1
            with:
              tag_name: ${{ github.ref_name }}
              name: ${{ github.ref_name }}
              prerelease: ${{ contains(github.ref_name, 'rc') }}
              generate_release_notes: true
              body: |
                ## Changelog
                ${{ needs.changelog.outputs.release-body }}
              files: |
                ./standalone.rbxm

    package:
        name: Packages
        runs-on: ubuntu-latest
        needs: changelog
        steps:
        - uses: actions/checkout@v4
          with:
            ref: main

        - id: get-version
          uses: battila7/get-version-action@v2

        - name: Bump package config
          uses: lumin-org/key-editor@v0.2.1
          with:
            key: 'version'
            content: ${{ steps.get-version.outputs.version-without-v }}
            files: |
              pesde.toml

        - name: Setup Pesde
          uses: lumin-org/setup-pesde@v0.4.1
          with:
            version: 'v0.6.0-rc.7+registry.0.2.0-rc.3'
            cache: true
            token: '${{ secrets.PESDE_TOKEN }}'

        - name: Install dependencies
          run: |
            pesde install

        - name: Publish packages
          run: |
            pesde publish -y

        - name: Commit package config
          uses: actions-js/push@v1.5
          with:
            rebase: true
            message: 'build(release): publish ${{ github.ref_name }}'
            github_token: ${{ secrets.GITHUB_TOKEN }}


